version: "3.9"

services:
 db:
    image: postgres:14-alpine
    volumes:
      - ../db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}"

 app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
        python manage.py wait_for_db &&
        python manage.py migrate &&
        python manage.py collectstatic --no-input &&  
        python manage.py compilemessages --ignore=venv &&
        gunicorn hands_of_friends.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - static_volume:/app/staticfiles
      - ../media:/app/media
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

 nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - ../media:/app/media
    ports:
      - "8080:8080"
    depends_on:
      - app

volumes:
 static_volume:
