# Generated by Django 5.0.1 on 2024-02-16 18:11

import validators.form_validation
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0002_alter_feedbackform_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackform",
            name="email",
            field=models.EmailField(
                max_length=254,
                validators=[validators.form_validation.validate_email_domain],
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackform",
            name="message",
            field=models.TextField(max_length=300, verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="feedbackform",
            name="name",
            field=models.CharField(
                validators=[validators.form_validation.validate_name],
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackform",
            name="phone_number",
            field=models.CharField(
                validators=[validators.form_validation.validate_phone_number],
                verbose_name="Phone number",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackform",
            name="sent_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Sent at"),
        ),
    ]
