# Generated by Django 5.0.1 on 2024-01-13 18:07

import content_management.upload_to_path
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_management", "0002_rename_main_text_tender_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField()),
                (
                    "image",
                    models.ImageField(
                        upload_to=content_management.upload_to_path.UploadToPath(
                            "project-images/"
                        )
                    ),
                ),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_active"],
            },
        ),
        migrations.AlterField(
            model_name="tender",
            name="title",
            field=models.CharField(),
        ),
    ]
