# Generated by Django 5.0.1 on 2024-01-14 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "content_management",
            "0005_project_description_en_project_description_uk_and_more",
        ),
    ]
