# Generated by Django 5.0.1 on 2024-01-16 15:48

import content_management.upload_to_path
import content_management.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_management", "0007_teammember_alter_project_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=content_management.upload_to_path.UploadToPath(
                            "partner-logos/"
                        ),
                        validators=[content_management.validators.validate_image],
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "partner logo",
                "verbose_name_plural": "partner logos",
                "ordering": ["-added_at"],
            },
        ),
    ]
