# Generated by Django 5.0.1 on 2024-01-16 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content_management", "0008_partnerlogo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-is_active", "-created_at"]},
        ),
    ]
