# Generated by Django 5.0.1 on 2024-01-18 19:17

import content_management.upload_to_path
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_management", "0009_alter_project_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partnerlogo",
            options={
                "ordering": ["company_name"],
                "verbose_name": "partner logo",
                "verbose_name_plural": "partner logos",
            },
        ),
        migrations.AddField(
            model_name="partnerlogo",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="partnerlogo",
            name="image",
            field=models.FileField(
                upload_to=content_management.upload_to_path.UploadToPath(
                    "partner-logos/"
                )
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.FileField(
                upload_to=content_management.upload_to_path.UploadToPath("projects/")
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="image",
            field=models.FileField(
                upload_to=content_management.upload_to_path.UploadToPath(
                    "team-members/"
                )
            ),
        ),
    ]
