# Generated by Django 5.0.1 on 2024-01-21 09:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "content_management",
            "0010_alter_partnerlogo_options_partnerlogo_company_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="tender",
            name="description_en",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="tender",
            name="description_uk",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
