# Generated by Django 5.0.1 on 2024-01-22 17:14

import content_management.upload_to_path
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "content_management",
            "0011_alter_tender_description_alter_tender_description_en_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        upload_to=content_management.upload_to_path.UploadToPath(
                            "news/"
                        )
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=255)),
                ("title_uk", models.CharField(max_length=255, null=True)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("description", models.TextField()),
                ("description_uk", models.TextField(null=True)),
                ("description_en", models.TextField(null=True)),
                ("link_to_news", models.URLField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "news",
                "ordering": ["-date"],
            },
        ),
    ]
