# Generated by Django 5.0.1 on 2024-01-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_management", "0012_news"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("youtube_link", models.URLField()),
                ("facebook_link", models.URLField()),
                ("address", models.CharField(max_length=255)),
                ("address_uk", models.CharField(max_length=255, null=True)),
                ("address_en", models.CharField(max_length=255, null=True)),
            ],
            options={
                "verbose_name_plural": "contacts",
            },
        ),
    ]
