# Generated by Django 5.0.1 on 2024-01-24 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content_management", "0013_contacts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tender",
            options={"ordering": ["-is_active", "-date"]},
        ),
    ]
