# Generated by Django 5.0.1 on 2024-01-25 12:01

import content_management.upload_to_path
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_management", "0015_pdfreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.FileField(
                upload_to=content_management.upload_to_path.UploadToPath("default/")
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_en",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_uk",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="partnerlogo",
            name="company_name",
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="partnerlogo",
            name="image",
            field=models.FileField(
                upload_to=content_management.upload_to_path.UploadToPath("default/")
            ),
        ),
        migrations.AlterField(
            model_name="pdfreport",
            name="file_url",
            field=models.FileField(
                upload_to=content_management.upload_to_path.UploadToPath("pdf-report/")
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.FileField(
                upload_to=content_management.upload_to_path.UploadToPath("default/")
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="image",
            field=models.FileField(
                upload_to=content_management.upload_to_path.UploadToPath("default/")
            ),
        ),
    ]
