# Generated by Django 5.0.1 on 2024-01-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_management", "0016_alter_news_image_alter_news_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.FileField(upload_to="news/"),
        ),
        migrations.AlterField(
            model_name="partnerlogo",
            name="image",
            field=models.FileField(upload_to="partner-logos/"),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.FileField(upload_to="projects/"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="image",
            field=models.FileField(upload_to="team-members/"),
        ),
    ]
