# Generated by Django 5.0.1 on 2024-01-29 20:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "content_management",
            "0017_alter_news_image_alter_partnerlogo_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="description_en",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="description_uk",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
