# Generated by Django 5.0.1 on 2024-01-29 20:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_management", "0018_alter_project_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tender",
            options={"ordering": ["-is_active", "-start_date"]},
        ),
        migrations.RenameField(
            model_name="tender",
            old_name="date",
            new_name="end_date",
        ),
        migrations.AddField(
            model_name="tender",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
