# Generated by Django 5.0.1 on 2024-02-10 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "content_management",
            "0019_alter_tender_options_rename_date_tender_end_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contacts",
            options={"verbose_name": "Contact", "verbose_name_plural": "Contacts"},
        ),
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-date"],
                "verbose_name": "News",
                "verbose_name_plural": "News",
            },
        ),
        migrations.AlterModelOptions(
            name="partnerlogo",
            options={
                "ordering": ["company_name"],
                "verbose_name": "Partner logo",
                "verbose_name_plural": "Partner logos",
            },
        ),
        migrations.AlterModelOptions(
            name="pdfreport",
            options={
                "verbose_name": "PDF report",
                "verbose_name_plural": "PDF reports",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-is_active", "-created_at"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.AlterModelOptions(
            name="teammember",
            options={
                "ordering": ["-added_at"],
                "verbose_name": "Team member",
                "verbose_name_plural": "Team members",
            },
        ),
        migrations.AlterModelOptions(
            name="tender",
            options={
                "ordering": ["-is_active", "-start_date"],
                "verbose_name": "Tender",
                "verbose_name_plural": "Tenders",
            },
        ),
    ]
