# Generated by Django 5.0.1 on 2024-02-10 16:16

import ckeditor.fields
import content_management.upload_to_path
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "content_management",
            "0020_alter_contacts_options_alter_news_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contacts",
            options={"verbose_name": "Контакт", "verbose_name_plural": "Контакти"},
        ),
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-date"],
                "verbose_name": "Новини",
                "verbose_name_plural": "Новини",
            },
        ),
        migrations.AlterModelOptions(
            name="partnerlogo",
            options={
                "ordering": ["company_name"],
                "verbose_name": "Логотип партнера",
                "verbose_name_plural": "Логотипи партнерів",
            },
        ),
        migrations.AlterModelOptions(
            name="pdfreport",
            options={
                "verbose_name": "PDF звітність",
                "verbose_name_plural": "PDF звітність",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-is_active", "-created_at"],
                "verbose_name": "Проєкт",
                "verbose_name_plural": "Проєкти",
            },
        ),
        migrations.AlterModelOptions(
            name="teammember",
            options={
                "ordering": ["-added_at"],
                "verbose_name": "Член команди",
                "verbose_name_plural": "Команда",
            },
        ),
        migrations.AlterModelOptions(
            name="tender",
            options={
                "ordering": ["-is_active", "-start_date"],
                "verbose_name": "Тендер",
                "verbose_name_plural": "Тендери",
            },
        ),
        migrations.AlterField(
            model_name="contacts",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Адреса"),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="address_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Адреса"),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="address_uk",
            field=models.CharField(max_length=255, null=True, verbose_name="Адреса"),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="facebook_link",
            field=models.URLField(verbose_name="Посилання на Facebook"),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="phone_number",
            field=models.CharField(max_length=255, verbose_name="Номер телефону"),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="youtube_link",
            field=models.URLField(verbose_name="Посилання на Youtube"),
        ),
        migrations.AlterField(
            model_name="news",
            name="added_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Додано"),
        ),
        migrations.AlterField(
            model_name="news",
            name="date",
            field=models.DateField(verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="news",
            name="description",
            field=models.TextField(verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="news",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="news",
            name="description_uk",
            field=models.TextField(null=True, verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.FileField(upload_to="news/", verbose_name="Зображення"),
        ),
        migrations.AlterField(
            model_name="news",
            name="link_to_news",
            field=models.URLField(verbose_name="Посилання на новини"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_en",
            field=models.CharField(null=True, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_uk",
            field=models.CharField(null=True, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="partnerlogo",
            name="added_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Додано"),
        ),
        migrations.AlterField(
            model_name="partnerlogo",
            name="company_name",
            field=models.CharField(
                default="Назва компанії",
                max_length=100,
                unique=True,
                verbose_name="Назва компанії",
            ),
        ),
        migrations.AlterField(
            model_name="partnerlogo",
            name="image",
            field=models.FileField(
                upload_to="partner-logos/", verbose_name="Зображення"
            ),
        ),
        migrations.AlterField(
            model_name="pdfreport",
            name="added_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Додано"),
        ),
        migrations.AlterField(
            model_name="pdfreport",
            name="file_url",
            field=models.FileField(
                upload_to=content_management.upload_to_path.UploadToPath("pdf-report/"),
                verbose_name="URL файлу",
            ),
        ),
        migrations.AlterField(
            model_name="pdfreport",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=ckeditor.fields.RichTextField(verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="project",
            name="description_en",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="project",
            name="description_uk",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.FileField(upload_to="projects/", verbose_name="Зображення"),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активний"),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="project",
            name="title_en",
            field=models.CharField(null=True, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="project",
            name="title_uk",
            field=models.CharField(null=True, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="added_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Додано"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Повне ім'я"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="full_name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Повне ім'я"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="full_name_uk",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Повне ім'я"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="image",
            field=models.FileField(
                upload_to="team-members/", verbose_name="Зображення"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="position",
            field=models.CharField(max_length=255, verbose_name="Посада"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="position_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Посада"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="position_uk",
            field=models.CharField(max_length=255, null=True, verbose_name="Посада"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="description",
            field=ckeditor.fields.RichTextField(verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="description_en",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="description_uk",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="end_date",
            field=models.DateField(verbose_name="Дата завершення"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активний"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="start_date",
            field=models.DateField(verbose_name="Дата початку"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="title",
            field=models.CharField(verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="title_en",
            field=models.CharField(null=True, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="title_uk",
            field=models.CharField(null=True, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
        ),
    ]
