# Generated by Django 5.0.1 on 2024-02-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "content_management",
            "0021_alter_contacts_options_alter_news_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DonorLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        upload_to="donors-logos/", verbose_name="Зображення"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Імʼя донора",
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Імʼя донора",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Імʼя донора",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Додано"),
                ),
            ],
            options={
                "verbose_name": "Логотип донора",
                "verbose_name_plural": "Логотипи донорів",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="partnerlogo",
            name="company_name_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Назва компанії"
            ),
        ),
        migrations.AddField(
            model_name="partnerlogo",
            name="company_name_uk",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Назва компанії"
            ),
        ),
        migrations.AlterField(
            model_name="partnerlogo",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Назва компанії"
            ),
        ),
    ]
