# Generated by Django 5.0.1 on 2024-02-10 19:49

import content_management.upload_to_path
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_management", "0022_donorlogo_partnerlogo_company_name_en_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pdfreport",
            options={"verbose_name": "Звітність", "verbose_name_plural": "Звітність"},
        ),
        migrations.AlterField(
            model_name="donorlogo",
            name="image",
            field=models.FileField(
                help_text="Зображення має бути у форматі .jpg, .jpeg, .webp, .png або .svg та не перевищувати 2 МБ.",
                upload_to="donors-logos/",
                verbose_name="Зображення",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.FileField(
                help_text="Зображення має бути у форматі .jpg, .jpeg, .webp, .png або .svg та не перевищувати 2 МБ.",
                upload_to="news/",
                verbose_name="Зображення",
            ),
        ),
        migrations.AlterField(
            model_name="partnerlogo",
            name="image",
            field=models.FileField(
                help_text="Зображення має бути у форматі .jpg, .jpeg, .webp, .png або .svg та не перевищувати 2 МБ.",
                upload_to="partner-logos/",
                verbose_name="Зображення",
            ),
        ),
        migrations.AlterField(
            model_name="pdfreport",
            name="file_url",
            field=models.FileField(
                help_text="Файл має бути у форматі .pdf та не перевищувати 2 МБ.",
                upload_to=content_management.upload_to_path.UploadToPath("pdf-report/"),
                verbose_name="URL файлу",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.FileField(
                help_text="Зображення має бути у форматі .jpg, .jpeg, .webp, .png або .svg та не перевищувати 2 МБ.",
                upload_to="projects/",
                verbose_name="Зображення",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="image",
            field=models.FileField(
                help_text="Зображення має бути у форматі .jpg, .jpeg, .webp, .png або .svg та не перевищувати 2 МБ.",
                upload_to="team-members/",
                verbose_name="Зображення",
            ),
        ),
    ]
