# Generated by Django 5.0.1 on 2024-02-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "content_management",
            "0025_alter_donorlogo_image_alter_donorlogo_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_shown",
            field=models.BooleanField(
                default=True,
                help_text="Позначте, якщо ви хочете, щоб цей об'єкт був видимим на сайті.",
                verbose_name="Показувати на сайті",
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="is_shown",
            field=models.BooleanField(
                default=True,
                help_text="Позначте, якщо ви хочете, щоб цей об'єкт був видимим на сайті.",
                verbose_name="Показувати на сайті",
            ),
        ),
    ]
