# Generated by Django 5.0.1 on 2024-02-13 13:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content_management", "0026_project_is_shown_tender_is_shown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=ckeditor.fields.RichTextField(
                help_text="Максимальна довжина тексту: 500 символів.",
                max_length=500,
                verbose_name="Short Description",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description_en",
            field=ckeditor.fields.RichTextField(
                help_text="Максимальна довжина тексту: 500 символів.",
                max_length=500,
                null=True,
                verbose_name="Short Description",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description_uk",
            field=ckeditor.fields.RichTextField(
                help_text="Максимальна довжина тексту: 500 символів.",
                max_length=500,
                null=True,
                verbose_name="Short Description",
            ),
        ),
    ]
