# Generated by Django 5.0.1 on 2024-02-13 15:27

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_management", "0027_alter_project_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=ckeditor.fields.RichTextField(
                help_text="Максимальна довжина тексту: 500 символів.",
                max_length=500,
                verbose_name="Короткий Опис",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description_en",
            field=ckeditor.fields.RichTextField(
                help_text="Максимальна довжина тексту: 500 символів.",
                max_length=500,
                null=True,
                verbose_name="Короткий Опис",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description_uk",
            field=ckeditor.fields.RichTextField(
                help_text="Максимальна довжина тексту: 500 символів.",
                max_length=500,
                null=True,
                verbose_name="Короткий Опис",
            ),
        ),
        migrations.CreateModel(
            name="ImageOrTextContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        help_text="Зображення має бути у форматі .jpg, .jpeg, .webp, .png або .svg та не перевищувати 2 МБ. Після завантаження зображення буде автоматично компресоване та змінено на формат .webp.",
                        null=True,
                        upload_to="project_contents/",
                        verbose_name="Зображення",
                    ),
                ),
                (
                    "text",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="Введіть контент.",
                        null=True,
                        verbose_name="Текст",
                    ),
                ),
                (
                    "text_uk",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="Введіть контент.",
                        null=True,
                        verbose_name="Текст",
                    ),
                ),
                (
                    "text_en",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="Введіть контент.",
                        null=True,
                        verbose_name="Текст",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="content_management.project",
                        verbose_name="Проєкт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контент",
                "verbose_name_plural": "Контент",
            },
        ),
    ]
