# Generated by Django 5.0.1 on 2024-02-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_management", "0028_alter_project_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="project",
            name="title_en",
            field=models.CharField(null=True, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="project",
            name="title_uk",
            field=models.CharField(null=True, verbose_name="Назва"),
        ),
    ]
