# Generated by Django 5.0.1 on 2024-02-13 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "content_management",
            "0029_alter_project_title_alter_project_title_en_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 2, 13, 18, 14, 53, 671822, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата завершення",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 2, 13, 18, 15, 0, 751741, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата початку",
            ),
            preserve_default=False,
        ),
    ]
