# Generated by Django 5.0.1 on 2024-02-15 11:05

import content_management.upload_to_path
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_management", "0030_project_end_date_project_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donorlogo",
            name="image",
            field=models.FileField(
                help_text="Зображення має бути у форматі .jpg, .jpeg, .webp, .png або .svg та не перевищувати 2 МБ. Після завантаження зображення буде автоматично компресоване та змінено на формат .webp.",
                upload_to=content_management.upload_to_path.UploadToPath(
                    "donors-logos/"
                ),
                verbose_name="Зображення",
            ),
        ),
        migrations.AlterField(
            model_name="imageortextcontent",
            name="image",
            field=models.FileField(
                blank=True,
                help_text="Зображення має бути у форматі .jpg, .jpeg, .webp, .png або .svg та не перевищувати 2 МБ. Після завантаження зображення буде автоматично компресоване та змінено на формат .webp.",
                null=True,
                upload_to=content_management.upload_to_path.UploadToPath(
                    "project_contents/"
                ),
                verbose_name="Зображення",
            ),
        ),
        migrations.AlterField(
            model_name="imageortextcontent",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content",
                to="content_management.project",
                verbose_name="Проєкт",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.FileField(
                help_text="Зображення має бути у форматі .jpg, .jpeg, .webp, .png або .svg та не перевищувати 2 МБ. Після завантаження зображення буде автоматично компресоване та змінено на формат .webp.",
                upload_to=content_management.upload_to_path.UploadToPath("news/"),
                verbose_name="Зображення",
            ),
        ),
        migrations.AlterField(
            model_name="partnerlogo",
            name="image",
            field=models.FileField(
                help_text="Зображення має бути у форматі .jpg, .jpeg, .webp, .png або .svg та не перевищувати 2 МБ. Після завантаження зображення буде автоматично компресоване та змінено на формат .webp.",
                upload_to=content_management.upload_to_path.UploadToPath(
                    "partner-logos/"
                ),
                verbose_name="Зображення",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.FileField(
                help_text="Зображення має бути у форматі .jpg, .jpeg, .webp, .png або .svg та не перевищувати 2 МБ. Після завантаження зображення буде автоматично компресоване та змінено на формат .webp.",
                upload_to=content_management.upload_to_path.UploadToPath("projects/"),
                verbose_name="Зображення",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="image",
            field=models.FileField(
                help_text="Зображення має бути у форматі .jpg, .jpeg, .webp, .png або .svg та не перевищувати 2 МБ. Після завантаження зображення буде автоматично компресоване та змінено на формат .webp.",
                upload_to=content_management.upload_to_path.UploadToPath(
                    "team-members/"
                ),
                verbose_name="Зображення",
            ),
        ),
    ]
