# Generated by Django 5.0.1 on 2024-02-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "content_management",
            "0032_alter_project_title_alter_project_title_en_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pdfreport",
            options={"verbose_name": "Document", "verbose_name_plural": "Documents"},
        ),
        migrations.AlterField(
            model_name="pdfreport",
            name="title",
            field=models.CharField(
                help_text="Максимальна довжина тексту: 200 символів.",
                max_length=200,
                verbose_name="Назва",
            ),
        ),
    ]
