# Generated by Django 5.0.1 on 2024-02-15 14:36

import content_management.upload_to_path
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_management", "0033_alter_pdfreport_options_alter_pdfreport_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Максимальна довжина тексту: 200 символів.",
                        max_length=200,
                        verbose_name="Назва",
                    ),
                ),
                (
                    "title_uk",
                    models.CharField(
                        help_text="Максимальна довжина тексту: 200 символів.",
                        max_length=200,
                        null=True,
                        verbose_name="Назва",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        help_text="Максимальна довжина тексту: 200 символів.",
                        max_length=200,
                        null=True,
                        verbose_name="Назва",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        help_text="Зображення має бути у форматі .jpg, .jpeg, .webp, .png або .svg та не перевищувати 2 МБ.",
                        upload_to=content_management.upload_to_path.UploadToPath(
                            "hero-slider/"
                        ),
                        verbose_name="Зображення",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Альтернативний текст для зображення. Максимальна довжина тексту: 100 символів.",
                        max_length=100,
                        null=True,
                        verbose_name="Alt Text",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hero Slider",
                "verbose_name_plural": "Hero Sliders",
            },
        ),
        migrations.AlterModelOptions(
            name="pdfreport",
            options={"verbose_name": "Документ", "verbose_name_plural": "Документи"},
        ),
    ]
