# Generated by Django 5.0.1 on 2024-02-15 15:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "content_management",
            "0035_alter_heroslider_options_heroslider_alt_text_en_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "history",
                    ckeditor.fields.RichTextField(
                        help_text="Максимальна довжина тексту: 2500 символів.",
                        max_length=2500,
                        verbose_name="Історія",
                    ),
                ),
                (
                    "history_uk",
                    ckeditor.fields.RichTextField(
                        help_text="Максимальна довжина тексту: 2500 символів.",
                        max_length=2500,
                        null=True,
                        verbose_name="Історія",
                    ),
                ),
                (
                    "history_en",
                    ckeditor.fields.RichTextField(
                        help_text="Максимальна довжина тексту: 2500 символів.",
                        max_length=2500,
                        null=True,
                        verbose_name="Історія",
                    ),
                ),
                (
                    "principles",
                    ckeditor.fields.RichTextField(
                        help_text="Максимальна довжина тексту: 2500 символів.",
                        max_length=2500,
                        verbose_name="Principles",
                    ),
                ),
                (
                    "principles_uk",
                    ckeditor.fields.RichTextField(
                        help_text="Максимальна довжина тексту: 2500 символів.",
                        max_length=2500,
                        null=True,
                        verbose_name="Principles",
                    ),
                ),
                (
                    "principles_en",
                    ckeditor.fields.RichTextField(
                        help_text="Максимальна довжина тексту: 2500 символів.",
                        max_length=2500,
                        null=True,
                        verbose_name="Principles",
                    ),
                ),
                (
                    "values",
                    ckeditor.fields.RichTextField(
                        help_text="Максимальна довжина тексту: 2500 символів.",
                        max_length=2500,
                        verbose_name="Values",
                    ),
                ),
                (
                    "values_uk",
                    ckeditor.fields.RichTextField(
                        help_text="Максимальна довжина тексту: 2500 символів.",
                        max_length=2500,
                        null=True,
                        verbose_name="Values",
                    ),
                ),
                (
                    "values_en",
                    ckeditor.fields.RichTextField(
                        help_text="Максимальна довжина тексту: 2500 символів.",
                        max_length=2500,
                        null=True,
                        verbose_name="Values",
                    ),
                ),
            ],
            options={
                "verbose_name": "About Us",
                "verbose_name_plural": "About Us",
            },
        ),
        migrations.AlterModelOptions(
            name="heroslider",
            options={
                "verbose_name": "Hero Cлайдер",
                "verbose_name_plural": "Hero Cлайдери",
            },
        ),
    ]
