# Generated by Django 5.0.1 on 2024-02-15 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "content_management",
            "0037_alter_aboutus_options_remove_news_link_to_news_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pdfreport",
            options={
                "ordering": ["title"],
                "verbose_name": "Документ",
                "verbose_name_plural": "Документи",
            },
        ),
    ]
