# Generated by Django 5.0.1 on 2024-02-15 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content_management", "0038_merge_20240215_1557"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="link_to_news",
        ),
    ]
