# Generated by Django 5.0.1 on 2024-02-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_management", "0040_alter_partnerlogo_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата завершення"
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата завершення"
            ),
        ),
    ]
