# Generated by Django 5.0.1 on 2024-02-18 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donorform",
            options={
                "ordering": ("-sent_at",),
                "verbose_name": "Donor form",
                "verbose_name_plural": "Donor forms",
            },
        ),
        migrations.AlterModelOptions(
            name="volunteerform",
            options={
                "ordering": ("-sent_at",),
                "verbose_name": "Volunteer form",
                "verbose_name_plural": "Volunteer forms",
            },
        ),
    ]
