# Generated by Django 5.0.1 on 2024-02-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backend",
                    models.CharField(
                        default="email_config.backends.CustomEmailBackend",
                        max_length=100,
                    ),
                ),
                ("host", models.CharField(default="smtp.gmail.com", max_length=100)),
                ("port", models.IntegerField(default=587)),
                ("use_tls", models.BooleanField(default=True)),
                ("host_user", models.EmailField(max_length=254)),
                ("host_password", models.CharField(max_length=100)),
                ("use_ssl", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
