# Generated by Django 5.0.1 on 2024-02-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email_config", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailsettings",
            options={
                "verbose_name": "Email Settings",
                "verbose_name_plural": "Email Settings",
            },
        ),
        migrations.AlterField(
            model_name="emailsettings",
            name="backend",
            field=models.CharField(
                default="email_config.backends.CustomEmailBackend",
                max_length=100,
                verbose_name="Backend",
            ),
        ),
        migrations.AlterField(
            model_name="emailsettings",
            name="host",
            field=models.CharField(
                default="smtp.gmail.com", max_length=100, verbose_name="Host"
            ),
        ),
        migrations.AlterField(
            model_name="emailsettings",
            name="host_password",
            field=models.CharField(max_length=100, verbose_name="Password"),
        ),
        migrations.AlterField(
            model_name="emailsettings",
            name="host_user",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="emailsettings",
            name="port",
            field=models.IntegerField(default=587, verbose_name="Port"),
        ),
        migrations.AlterField(
            model_name="emailsettings",
            name="use_ssl",
            field=models.BooleanField(default=False, verbose_name="Use SSL"),
        ),
        migrations.AlterField(
            model_name="emailsettings",
            name="use_tls",
            field=models.BooleanField(default=True, verbose_name="Use TLS"),
        ),
    ]
