# Generated by Django 5.0.1 on 2024-02-18 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("email_config", "0002_alter_emailsettings_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipient",
            options={"verbose_name": "Recipient", "verbose_name_plural": "Recipients"},
        ),
    ]
